Add comment for ftdetect python wheels

diff --git a/install.d/005-all-xdg-symlinks b/install.d/005-all-xdg-symlinks
--- a/install.d/005-all-xdg-symlinks
+++ b/install.d/005-all-xdg-symlinks
@@ -2,14 +2,16 @@
 #
 
 # shellcheck disable=SC2154
-if [[ ! -d $dotfiles_dest ]]; then echo "dotfiles_dest var not found: $dotfiles_dest" 1>&2; return 1; fi
+if [[ ! -d "$(realpath "$dotfiles_dest")" ]]; then echo "dotfiles_dest var not found: $dotfiles_dest" 1>&2; return 1; fi
 
 if ! command -v find &> /dev/null; then echo "Missing dependency: find" 1>&2; return 1; fi
 
 main() {
-  if cd "$HOME" ; then
-    find "$dotfiles_dest/home/" -maxdepth 1 -mindepth 1 -exec ln -s {} \;
-  fi
+  (
+    if cd "$HOME" ; then
+      find "$dotfiles_dest/home/" -maxdepth 1 -mindepth 1 -type f -exec ln -s {} \;
+    fi
+  )
 }
 
 main "$@"
