Never exit 1; always return $?
Fixes #61
Fixes #74

diff --git a/install.d/005-all-xdg-symlinks b/install.d/005-all-xdg-symlinks
--- a/install.d/005-all-xdg-symlinks
+++ b/install.d/005-all-xdg-symlinks
@@ -9,15 +9,15 @@
 #
 
 # shellcheck disable=SC2154
-if [[ ! -d $dotfiles_dest ]]; then echo "dotfiles_dest var not found: $dotfiles_dest" 1>&2; exit 1; fi
+if [[ ! -d $dotfiles_dest ]]; then echo "dotfiles_dest var not found: $dotfiles_dest" 1>&2; return 1; fi
 
-if ! command -v find &> /dev/null; then echo "Missing dependency: find" 1>&2; exit 1; fi
+if ! command -v find &> /dev/null; then echo "Missing dependency: find" 1>&2; return 1; fi
 
 main() {
-  cd "$HOME" || return 1
-  find "$dotfiles_dest/home/" -maxdepth 1 -mindepth 1 -exec ln -s {} \; || return 1
+  cd "$HOME" || return $?
+  find "$dotfiles_dest/home/" -maxdepth 1 -mindepth 1 -exec ln -s {} \; || return $?
 }
 
 main "$@"
-exit "$?"
+return "$?"
 # vim: filetype=sh foldmethod=marker shiftwidth=2 expandtab softtabstop=4:
