Print errors if a git config command dies

diff --git a/install.d/105-all-gitconfig b/install.d/105-all-gitconfig
--- a/install.d/105-all-gitconfig
+++ b/install.d/105-all-gitconfig
@@ -1,6 +1,7 @@
-#!/usr/bin/env sh
+#!/usr/bin/env bash
 #
 set -e
+trap 'echo "Command failed: '\''$BASH_COMMAND'\'' (exit status: $?)"' ERR
 
 git config --global user.name "Ryan Delaney"
 git config --global user.email "ryan.patrick.delaney+git@protonmail.com"
